# Generated by Django 5.2.7 on 2026-02-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcreationrequest',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
