# Generated by Django 5.2.7 on 2026-03-03 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CID',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CID must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
    ]
