# Generated by Django 5.2.7 on 2026-03-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_groupcreationrequest_group_name_and_more'),
        ('core', '0003_companytype_sector_program_duration_externalcompany_and_more'),
    ]

    operations = [
    ]
