# Generated by Django 4.2.16 on 2026-03-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_cid'),
        ('core', '0005_merge_20260301_1516'),
    ]

    operations = [
    ]
