# Generated by Django 5.2.7 on 2026-02-17 07:23

import django.db.models.deletion
from django.db import migrations, models
from django.db import connection


def forwards(apps, schema_editor):
    Project = apps.get_model('core', 'Project')
    ProjectState = apps.get_model('core', 'ProjectState')
    conn = schema_editor.connection
    cursor = conn.cursor()
    # check column existence first (some partially-applied runs may have removed it)
    cursor.execute(
        "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s",
        ['core_project', 'state']
    )
    if cursor.fetchone()[0] == 0:
        return

    # fetch distinct current state values (strings)
    cursor.execute("SELECT DISTINCT `state` FROM `core_project`")
    rows = cursor.fetchall()
    for (state_val,) in rows:
        if state_val is None or str(state_val).strip() == '':
            continue
        # create a ProjectState for each distinct state name
        ps, created = ProjectState.objects.using(conn.alias).get_or_create(name=state_val)
        # update projects to reference the new id (store numeric id as string so ALTER COLUMN can convert)
        cursor.execute("UPDATE `core_project` SET `state` = %s WHERE `state` = %s", [str(ps.ProjectStateId), state_val])


def reverse(apps, schema_editor):
    ProjectState = apps.get_model('core', 'ProjectState')
    conn = schema_editor.connection
    cursor = conn.cursor()
    # check column existence first
    cursor.execute(
        "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s",
        ['core_project', 'state']
    )
    if cursor.fetchone()[0] == 0:
        return

    # restore string names back from ProjectState rows
    for ps in ProjectState.objects.using(conn.alias).all():
        cursor.execute("UPDATE `core_project` SET `state` = %s WHERE `state` = %s", [ps.name, str(ps.ProjectStateId)])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_department'),
    ]

    operations = [
        # Ensure leftover table from previous failed run is removed so CreateModel can succeed
        migrations.RunSQL("DROP TABLE IF EXISTS `core_projectstate`;", reverse_sql=migrations.RunSQL.noop),

        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('ProjectStateId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        # Data migration: convert existing string states into ProjectState rows
        migrations.RunPython(forwards, reverse),
        migrations.RemoveField(
            model_name='group',
            name='department',
        ),
        migrations.RemoveField(
            model_name='group',
            name='program',
        ),
        migrations.RemoveField(
            model_name='project',
            name='college',
        ),
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.projectstate'),
        ),
        migrations.CreateModel(
            name='programProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_projects', to='core.program')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_projects', to='core.project')),
            ],
            options={
                'verbose_name_plural': 'Program Projects',
                'unique_together': {('program', 'project')},
            },
        ),
    ]
