# Generated by Django 5.2.7 on 2026-02-22 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_projectstate_remove_group_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='End Year'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='Start Year'),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='programgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_groups', to='core.group')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_groups', to='core.program')),
            ],
            options={
                'verbose_name_plural': 'Program Groups',
                'unique_together': {('program', 'group')},
            },
        ),
        migrations.DeleteModel(
            name='programProject',
        ),
    ]
