# Generated by Django 5.2.7 on 2026-02-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_contactus'),
        ('core', '0022_remove_group_group_name_alter_project_end_date_and_more'),
    ]

    operations = [
    ]
