# Generated by Django 5.2.7 on 2026-02-23 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20260222_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Documentation_Path',
            field=models.TextField(blank=True, null=True, verbose_name='Documentation Path'),
        ),
        migrations.AddField(
            model_name='project',
            name='Logo',
            field=models.TextField(blank=True, null=True, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='project',
            name='field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('Qualification', models.TextField(blank=True, null=True)),
                ('Office_Hours', models.TextField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
