# Generated by Django 5.2.7 on 2026-02-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_project_documentation_path_project_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcreationrequest',
            name='group_name',
        ),
    ]
